"""Legacy Minecraft (LCE) block + item id -> friendly name tables.

Data only — Minecraft's own numbering (legacy console/Java ids), baked from the
public id tables so the GUI's name-search dropdowns don't need to memorize numbers.
`search(query, kind)` powers the searchable comboboxes.
"""

BLOCK_NAMES = {
    1: 'Stone',
    2: 'Grass Block',
    3: 'Dirt',
    4: 'Cobblestone',
    5: 'Oak Planks',
    6: 'Oak Sapling',
    7: 'Bedrock',
    8: 'Water',
    9: 'Water',
    10: 'Lava',
    11: 'Lava',
    12: 'Sand',
    13: 'Gravel',
    14: 'Gold Ore',
    15: 'Iron Ore',
    16: 'Coal Ore',
    17: 'Oak Log',
    18: 'Oak Leaves',
    19: 'Sponge',
    20: 'Glass',
    21: 'Lapis Ore',
    22: 'Lapis Block',
    23: 'Dispenser',
    24: 'Sandstone',
    25: 'Note Block',
    26: 'Red Bed',
    27: 'Powered Rail',
    28: 'Detector Rail',
    29: 'Sticky Piston',
    30: 'Cobweb',
    31: 'Dead Bush',
    32: 'Dead Bush',
    33: 'Piston',
    34: 'Piston Head',
    35: 'White Wool',
    36: 'Moving Piston',
    37: 'Dandelion',
    38: 'Poppy',
    39: 'Brown Mushroom',
    40: 'Red Mushroom',
    41: 'Gold Block',
    42: 'Iron Block',
    43: 'Stone Slab',
    44: 'Stone Slab',
    45: 'Bricks',
    46: 'TNT',
    47: 'Bookshelf',
    48: 'Mossy Cobblestone',
    49: 'Obsidian',
    50: 'Torch',
    51: 'Fire',
    52: 'Spawner',
    53: 'Oak Stairs',
    54: 'Chest',
    55: 'Redstone Wire',
    56: 'Diamond Ore',
    57: 'Diamond Block',
    58: 'Crafting Table',
    59: 'Wheat',
    60: 'Farmland',
    61: 'Furnace',
    62: 'Furnace',
    63: 'Sign',
    64: 'Oak Door',
    65: 'Ladder',
    66: 'Rail',
    67: 'Cobblestone Stairs',
    68: 'Wall Sign',
    69: 'Lever',
    70: 'Stone Pressure Plate',
    71: 'Iron Door',
    72: 'Oak Pressure Plate',
    73: 'Redstone Ore',
    74: 'Redstone Ore',
    75: 'Redstone Wall Torch',
    76: 'Redstone Wall Torch',
    77: 'Stone Button',
    78: 'Snow',
    79: 'Ice',
    80: 'Snow Block',
    81: 'Cactus',
    82: 'Clay',
    83: 'Sugar Cane',
    84: 'Jukebox',
    85: 'Oak Fence',
    86: 'Carved Pumpkin',
    87: 'Netherrack',
    88: 'Soul Sand',
    89: 'Glowstone',
    90: 'Nether Portal',
    91: 'Jack O Lantern',
    92: 'Cake',
    93: 'Repeater',
    94: 'Repeater',
    95: 'White Stained Glass',
    96: 'Oak Trapdoor',
    97: 'Infested Stone',
    98: 'Stone Bricks',
    99: 'Brown Mushroom Block',
    100: 'Red Mushroom Block',
    101: 'Iron Bars',
    102: 'Glass Pane',
    103: 'Melon',
    104: 'Pumpkin Stem',
    105: 'Melon Stem',
    106: 'Vine',
    107: 'Oak Fence Gate',
    108: 'Brick Stairs',
    109: 'Stone Brick Stairs',
    110: 'Mycelium',
    111: 'Lily Pad',
    112: 'Nether Bricks',
    113: 'Nether Brick Fence',
    114: 'Nether Brick Stairs',
    115: 'Nether Wart',
    116: 'Enchanting Table',
    117: 'Brewing Stand',
    118: 'Cauldron',
    119: 'End Portal',
    120: 'End Portal Frame',
    121: 'End Stone',
    122: 'Dragon Egg',
    123: 'Redstone Lamp',
    124: 'Redstone Lamp',
    125: 'Oak Slab',
    126: 'Oak Slab',
    127: 'Cocoa',
    128: 'Sandstone Stairs',
    129: 'Emerald Ore',
    130: 'Ender Chest',
    131: 'Tripwire Hook',
    132: 'Tripwire',
    133: 'Emerald Block',
    134: 'Spruce Stairs',
    135: 'Birch Stairs',
    136: 'Jungle Stairs',
    138: 'Beacon',
    139: 'Cobblestone Wall',
    140: 'Flower Pot',
    141: 'Carrots',
    142: 'Potatoes',
    143: 'Oak Button',
    144: 'Skeleton Skull',
    145: 'Anvil',
    146: 'Trapped Chest',
    147: 'Light Weighted Pressure Plate',
    148: 'Heavy Weighted Pressure Plate',
    149: 'Comparator',
    150: 'Comparator',
    151: 'Daylight Detector',
    152: 'Redstone Block',
    153: 'Nether Quartz Ore',
    154: 'Hopper',
    155: 'Quartz Block',
    156: 'Quartz Stairs',
    157: 'Activator Rail',
    158: 'Dropper',
    159: 'White Terracotta',
    160: 'White Stained Glass Pane',
    161: 'Acacia Leaves',
    162: 'Acacia Log',
    163: 'Acacia Stairs',
    164: 'Dark Oak Stairs',
    165: 'Slime Block',
    166: 'Barrier',
    167: 'Iron Trapdoor',
    168: 'Prismarine',
    169: 'Sea Lantern',
    170: 'Hay Block',
    171: 'White Carpet',
    172: 'Terracotta',
    173: 'Coal Block',
    174: 'Packed Ice',
    175: 'Sunflower',
    176: 'White Banner',
    177: 'White Wall Banner',
    178: 'Daylight Detector',
    179: 'Red Sandstone',
    180: 'Red Sandstone Stairs',
    181: 'Red Sandstone Slab',
    182: 'Red Sandstone Slab',
    183: 'Spruce Fence Gate',
    184: 'Birch Fence Gate',
    185: 'Jungle Fence Gate',
    186: 'Dark Oak Fence Gate',
    187: 'Acacia Fence Gate',
    188: 'Spruce Fence',
    189: 'Birch Fence',
    190: 'Jungle Fence',
    191: 'Dark Oak Fence',
    192: 'Acacia Fence',
    193: 'Spruce Door',
    194: 'Birch Door',
    195: 'Jungle Door',
    196: 'Acacia Door',
    197: 'Dark Oak Door',
    198: 'End Rod',
    199: 'Chorus Plant',
    200: 'Chorus Flower',
    201: 'Purpur Block',
    202: 'Purpur Pillar',
    203: 'Purpur Stairs',
    204: 'Purpur Slab',
    205: 'Purpur Slab',
    206: 'End Stone Bricks',
    207: 'Beetroots',
    208: 'Grass Path',
    209: 'End Gateway',
    212: 'Frosted Ice',
    213: 'Magma Block',
    214: 'Nether Wart Block',
    215: 'Red Nether Bricks',
    216: 'Bone Block',
    218: 'Observer',
    219: 'White Shulker Box',
    220: 'Orange Shulker Box',
    221: 'Magenta Shulker Box',
    222: 'Light Blue Shulker Box',
    223: 'Yellow Shulker Box',
    224: 'Lime Shulker Box',
    225: 'Pink Shulker Box',
    226: 'Gray Shulker Box',
    227: 'Light Gray Shulker Box',
    228: 'Cyan Shulker Box',
    229: 'Purple Shulker Box',
    230: 'Blue Shulker Box',
    231: 'Brown Shulker Box',
    232: 'Green Shulker Box',
    233: 'Red Shulker Box',
    234: 'Black Shulker Box',
    235: 'White Glazed Terracotta',
    236: 'Orange Glazed Terracotta',
    237: 'Magenta Glazed Terracotta',
    238: 'Light Blue Glazed Terracotta',
    239: 'Yellow Glazed Terracotta',
    240: 'Lime Glazed Terracotta',
    241: 'Pink Glazed Terracotta',
    242: 'Gray Glazed Terracotta',
    243: 'Light Gray Glazed Terracotta',
    244: 'Cyan Glazed Terracotta',
    245: 'Purple Glazed Terracotta',
    246: 'Blue Glazed Terracotta',
    247: 'Brown Glazed Terracotta',
    248: 'Green Glazed Terracotta',
    249: 'Red Glazed Terracotta',
    250: 'Black Glazed Terracotta',
    251: 'White Concrete',
    252: 'White Concrete Powder',
}

ITEM_NAMES = {
    1: 'Stone',
    2: 'Grass Block',
    3: 'Dirt',
    4: 'Cobblestone',
    5: 'Oak Planks',
    6: 'Oak Sapling',
    7: 'Bedrock',
    8: 'Water',
    9: 'Water',
    10: 'Lava',
    11: 'Lava',
    12: 'Sand',
    13: 'Gravel',
    14: 'Gold Ore',
    15: 'Iron Ore',
    16: 'Coal Ore',
    17: 'Oak Log',
    18: 'Oak Leaves',
    19: 'Sponge',
    20: 'Glass',
    21: 'Lapis Ore',
    22: 'Lapis Block',
    23: 'Dispenser',
    24: 'Sandstone',
    25: 'Note Block',
    26: 'Red Bed',
    27: 'Powered Rail',
    28: 'Detector Rail',
    29: 'Sticky Piston',
    30: 'Cobweb',
    31: 'Dead Bush',
    32: 'Dead Bush',
    33: 'Piston',
    34: 'Piston Head',
    35: 'White Wool',
    36: 'Moving Piston',
    37: 'Dandelion',
    38: 'Poppy',
    39: 'Brown Mushroom',
    40: 'Red Mushroom',
    41: 'Gold Block',
    42: 'Iron Block',
    43: 'Stone Slab',
    44: 'Stone Slab',
    45: 'Bricks',
    46: 'TNT',
    47: 'Bookshelf',
    48: 'Mossy Cobblestone',
    49: 'Obsidian',
    50: 'Torch',
    51: 'Fire',
    52: 'Spawner',
    53: 'Oak Stairs',
    54: 'Chest',
    55: 'Redstone Wire',
    56: 'Diamond Ore',
    57: 'Diamond Block',
    58: 'Crafting Table',
    59: 'Wheat',
    60: 'Farmland',
    61: 'Furnace',
    62: 'Furnace',
    63: 'Sign',
    64: 'Oak Door',
    65: 'Ladder',
    66: 'Rail',
    67: 'Cobblestone Stairs',
    68: 'Wall Sign',
    69: 'Lever',
    70: 'Stone Pressure Plate',
    71: 'Iron Door',
    72: 'Oak Pressure Plate',
    73: 'Redstone Ore',
    74: 'Redstone Ore',
    75: 'Redstone Wall Torch',
    76: 'Redstone Wall Torch',
    77: 'Stone Button',
    78: 'Snow',
    79: 'Ice',
    80: 'Snow Block',
    81: 'Cactus',
    82: 'Clay',
    83: 'Sugar Cane',
    84: 'Jukebox',
    85: 'Oak Fence',
    86: 'Carved Pumpkin',
    87: 'Netherrack',
    88: 'Soul Sand',
    89: 'Glowstone',
    90: 'Nether Portal',
    91: 'Jack O Lantern',
    92: 'Cake',
    93: 'Repeater',
    94: 'Repeater',
    95: 'White Stained Glass',
    96: 'Oak Trapdoor',
    97: 'Infested Stone',
    98: 'Stone Bricks',
    99: 'Brown Mushroom Block',
    100: 'Red Mushroom Block',
    101: 'Iron Bars',
    102: 'Glass Pane',
    103: 'Melon',
    104: 'Pumpkin Stem',
    105: 'Melon Stem',
    106: 'Vine',
    107: 'Oak Fence Gate',
    108: 'Brick Stairs',
    109: 'Stone Brick Stairs',
    110: 'Mycelium',
    111: 'Lily Pad',
    112: 'Nether Bricks',
    113: 'Nether Brick Fence',
    114: 'Nether Brick Stairs',
    115: 'Nether Wart',
    116: 'Enchanting Table',
    117: 'Brewing Stand',
    118: 'Cauldron',
    119: 'End Portal',
    120: 'End Portal Frame',
    121: 'End Stone',
    122: 'Dragon Egg',
    123: 'Redstone Lamp',
    124: 'Redstone Lamp',
    125: 'Oak Slab',
    126: 'Oak Slab',
    127: 'Cocoa',
    128: 'Sandstone Stairs',
    129: 'Emerald Ore',
    130: 'Ender Chest',
    131: 'Tripwire Hook',
    132: 'Tripwire',
    133: 'Emerald Block',
    134: 'Spruce Stairs',
    135: 'Birch Stairs',
    136: 'Jungle Stairs',
    138: 'Beacon',
    139: 'Cobblestone Wall',
    140: 'Flower Pot',
    141: 'Carrots',
    142: 'Potatoes',
    143: 'Oak Button',
    144: 'Skeleton Skull',
    145: 'Anvil',
    146: 'Trapped Chest',
    147: 'Light Weighted Pressure Plate',
    148: 'Heavy Weighted Pressure Plate',
    149: 'Comparator',
    150: 'Comparator',
    151: 'Daylight Detector',
    152: 'Redstone Block',
    153: 'Nether Quartz Ore',
    154: 'Hopper',
    155: 'Quartz Block',
    156: 'Quartz Stairs',
    157: 'Activator Rail',
    158: 'Dropper',
    159: 'White Terracotta',
    160: 'White Stained Glass Pane',
    161: 'Acacia Leaves',
    162: 'Acacia Log',
    163: 'Acacia Stairs',
    164: 'Dark Oak Stairs',
    165: 'Slime Block',
    166: 'Barrier',
    167: 'Iron Trapdoor',
    168: 'Prismarine',
    169: 'Sea Lantern',
    170: 'Hay Block',
    171: 'White Carpet',
    172: 'Terracotta',
    173: 'Coal Block',
    174: 'Packed Ice',
    175: 'Sunflower',
    176: 'White Banner',
    177: 'White Wall Banner',
    178: 'Daylight Detector',
    179: 'Red Sandstone',
    180: 'Red Sandstone Stairs',
    181: 'Red Sandstone Slab',
    182: 'Red Sandstone Slab',
    183: 'Spruce Fence Gate',
    184: 'Birch Fence Gate',
    185: 'Jungle Fence Gate',
    186: 'Dark Oak Fence Gate',
    187: 'Acacia Fence Gate',
    188: 'Spruce Fence',
    189: 'Birch Fence',
    190: 'Jungle Fence',
    191: 'Dark Oak Fence',
    192: 'Acacia Fence',
    193: 'Spruce Door',
    194: 'Birch Door',
    195: 'Jungle Door',
    196: 'Acacia Door',
    197: 'Dark Oak Door',
    198: 'End Rod',
    199: 'Chorus Plant',
    200: 'Chorus Flower',
    201: 'Purpur Block',
    202: 'Purpur Pillar',
    203: 'Purpur Stairs',
    204: 'Purpur Slab',
    205: 'Purpur Slab',
    206: 'End Stone Bricks',
    207: 'Beetroots',
    208: 'Grass Path',
    209: 'End Gateway',
    212: 'Frosted Ice',
    213: 'Magma Block',
    214: 'Nether Wart Block',
    215: 'Red Nether Bricks',
    216: 'Bone Block',
    218: 'Observer',
    219: 'White Shulker Box',
    220: 'Orange Shulker Box',
    221: 'Magenta Shulker Box',
    222: 'Light Blue Shulker Box',
    223: 'Yellow Shulker Box',
    224: 'Lime Shulker Box',
    225: 'Pink Shulker Box',
    226: 'Gray Shulker Box',
    227: 'Light Gray Shulker Box',
    228: 'Cyan Shulker Box',
    229: 'Purple Shulker Box',
    230: 'Blue Shulker Box',
    231: 'Brown Shulker Box',
    232: 'Green Shulker Box',
    233: 'Red Shulker Box',
    234: 'Black Shulker Box',
    235: 'White Glazed Terracotta',
    236: 'Orange Glazed Terracotta',
    237: 'Magenta Glazed Terracotta',
    238: 'Light Blue Glazed Terracotta',
    239: 'Yellow Glazed Terracotta',
    240: 'Lime Glazed Terracotta',
    241: 'Pink Glazed Terracotta',
    242: 'Gray Glazed Terracotta',
    243: 'Light Gray Glazed Terracotta',
    244: 'Cyan Glazed Terracotta',
    245: 'Purple Glazed Terracotta',
    246: 'Blue Glazed Terracotta',
    247: 'Brown Glazed Terracotta',
    248: 'Green Glazed Terracotta',
    249: 'Red Glazed Terracotta',
    250: 'Black Glazed Terracotta',
    251: 'White Concrete',
    252: 'White Concrete Powder',
    256: 'Iron Shovel',
    257: 'Iron Pickaxe',
    258: 'Iron Axe',
    259: 'Flint & Steel',
    260: 'Apple',
    261: 'Bow',
    262: 'Arrow',
    263: 'Coal',
    264: 'Diamond',
    265: 'Iron Ingot',
    266: 'Gold Ingot',
    267: 'Iron Sword',
    268: 'Wooden Sword',
    269: 'Wooden Shovel',
    270: 'Wooden Pickaxe',
    271: 'Wooden Axe',
    272: 'Stone Sword',
    273: 'Stone Shovel',
    274: 'Stone Pickaxe',
    275: 'Stone Axe',
    276: 'Diamond Sword',
    277: 'Diamond Shovel',
    278: 'Diamond Pickaxe',
    279: 'Diamond Axe',
    280: 'Stick',
    281: 'Bowl',
    282: 'Mushroom Stew',
    283: 'Golden Sword',
    284: 'Golden Shovel',
    285: 'Golden Pickaxe',
    286: 'Golden Axe',
    287: 'String',
    288: 'Feather',
    289: 'Gunpowder',
    290: 'Wooden Hoe',
    291: 'Stone Hoe',
    292: 'Iron Hoe',
    293: 'Diamond Hoe',
    294: 'Golden Hoe',
    295: 'Seeds',
    296: 'Wheat',
    297: 'Bread',
    298: 'Leather Cap',
    299: 'Leather Tunic',
    300: 'Leather Pants',
    301: 'Leather Boots',
    302: 'Chainmail Helmet',
    303: 'Chainmail Chestplate',
    304: 'Chainmail Leggings',
    305: 'Chainmail Boots',
    306: 'Iron Helmet',
    307: 'Iron Chestplate',
    308: 'Iron Leggings',
    309: 'Iron Boots',
    310: 'Diamond Helmet',
    311: 'Diamond Chestplate',
    312: 'Diamond Leggings',
    313: 'Diamond Boots',
    314: 'Golden Helmet',
    315: 'Golden Chestplate',
    316: 'Golden Leggings',
    317: 'Golden Boots',
    318: 'Flint',
    319: 'Raw Porkchop',
    320: 'Cooked Porkchop',
    321: 'Painting',
    322: 'Golden Apple',
    323: 'Sign',
    324: 'Wooden Door',
    325: 'Bucket',
    326: 'Water Bucket',
    327: 'Lava Bucket',
    328: 'Minecart',
    329: 'Saddle',
    330: 'Iron Door',
    331: 'Redstone',
    332: 'Snowball',
    333: 'Boat',
    334: 'Leather',
    335: 'Milk Bucket',
    336: 'Brick',
    337: 'Clay',
    338: 'Sugar Cane',
    339: 'Paper',
    340: 'Book',
    341: 'Slimeball',
    342: 'Storage Minecart',
    343: 'Powered Minecart',
    344: 'Egg',
    345: 'Compass',
    346: 'Fishing Rod',
    347: 'Clock',
    348: 'Glowstone Dust',
    349: 'Raw Fish',
    350: 'Cooked Fish',
    351: 'Dye',
    352: 'Bone',
    353: 'Sugar',
    354: 'Cake',
    355: 'Bed',
    356: 'Redstone Repeater',
    357: 'Cookie',
    358: 'Map',
    359: 'Shears',
    360: 'Melon',
    361: 'Pumpkin Seeds',
    362: 'Melon Seeds',
    363: 'Raw Beef',
    364: 'Steak',
    365: 'Raw Chicken',
    366: 'Cooked Chicken',
    367: 'Rotten Flesh',
    368: 'Ender Pearl',
    369: 'Blaze Rod',
    370: 'Ghast Tear',
    371: 'Gold Nugget',
    372: 'Nether Wart',
    373: 'Potion',
    374: 'Glass Bottle',
    375: 'Spider Eye',
    376: 'Fermented Spider Eye',
    377: 'Blaze Powder',
    378: 'Magma Cream',
    379: 'Brewing Stand',
    380: 'Cauldron',
    381: 'Eye Of Ender',
    382: 'Glistering Melon',
    383: 'Spawn Egg',
    384: 'XP Bottle',
    385: 'Fire Charge',
    386: 'Book And Quill',
    387: 'Written Book',
    388: 'Emerald',
    389: 'Item Frame',
    390: 'Flower Pot',
    391: 'Carrot',
    392: 'Potato',
    393: 'Baked Potato',
    394: 'Poisonous Potato',
    395: 'Map',
    396: 'Golden Carrot',
    398: 'Carrot On A Stick',
    399: 'Nether Star',
    400: 'Pumpkin Pie',
    401: 'Firework Rocket',
    402: 'Firework Charge',
    403: 'Enchanted Book',
    404: 'Comparator',
    405: 'Nether Brick',
    406: 'Quartz',
    407: 'TNT Minecart',
    408: 'Hopper Minecart',
    409: 'Prismarine Shard',
    410: 'Prismarine Crystals',
    411: 'Rabbit',
    412: 'Cooked Rabbit',
    413: 'Rabbit Stew',
    414: 'Rabbit Foot',
    415: 'Rabbit Hide',
    416: 'Armor Stand',
    417: 'Iron Horse Armor',
    418: 'Golden Horse Armor',
    419: 'Diamond Horse Armor',
    420: 'Lead',
    421: 'Name Tag',
    422: 'Command Block Minecart',
    423: 'Mutton',
    424: 'Cooked Mutton',
    425: 'Banner',
    426: 'End Crystal',
    427: 'Spruce Door',
    428: 'Birch Door',
    429: 'Jungle Door',
    430: 'Acacia Door',
    431: 'Dark Oak Door',
    432: 'Chorus Fruit',
    433: 'Popped Chorus Fruit',
    434: 'Beetroot',
    435: 'Beetroot Seeds',
    436: 'Beetroot Soup',
    437: 'Dragon Breath',
    438: 'Splash Potion',
    440: 'Tipped Arrow',
    441: 'Lingering Potion',
    443: 'Elytra',
    444: 'Spruce Boat',
    445: 'Birch Boat',
    446: 'Jungle Boat',
    447: 'Acacia Boat',
    448: 'Dark Oak Boat',
    449: 'Totem Of Undying',
    450: 'Shulker Shell',
    452: 'Iron Nugget',
    453: 'Leather Horse Armor',
    2256: 'Music Disc',
    2257: 'Music Disc',
    2258: 'Music Disc',
    2259: 'Music Disc Chirp',
    2260: 'Music Disc Far',
    2261: 'Music Disc Mall',
    2262: 'Music Disc Mellohi',
    2263: 'Music Disc Stal',
    2264: 'Music Disc Strad',
    2265: 'Music Disc Ward',
    2266: 'Music Disc 11',
    2267: 'Music Disc Wait',
}


def _index(table):
    return [(f"{nm}  ({i})", i, nm.lower()) for i, nm in sorted(table.items(), key=lambda kv: kv[1])]

BLOCK_INDEX = _index(BLOCK_NAMES)
ITEM_INDEX = _index(ITEM_NAMES)

# Spawnable mobs as (friendly label, LCE entity-id string). The id is what the game
# stores — several differ from the display name (Iron Golem = VillagerGolem, Magma Cube
# = LavaSlime, Ocelot = Ozelot, Horse = EntityHorse, Wither = WitherBoss, Zombie Pigman
# = PigZombie). CamelCase = the classic (pre-TU54) spelling used across most LCE saves.
MOBS = [
    ("Bat", "Bat"), ("Blaze", "Blaze"), ("Cave Spider", "CaveSpider"), ("Chicken", "Chicken"),
    ("Cow", "Cow"), ("Creeper", "Creeper"), ("Enderman", "Enderman"), ("Endermite", "Endermite"),
    ("Ghast", "Ghast"), ("Giant", "Giant"), ("Guardian", "Guardian"), ("Horse", "EntityHorse"),
    ("Iron Golem", "VillagerGolem"), ("Magma Cube", "LavaSlime"), ("Mooshroom", "MushroomCow"),
    ("Ocelot", "Ozelot"), ("Pig", "Pig"), ("Rabbit", "Rabbit"), ("Sheep", "Sheep"),
    ("Silverfish", "Silverfish"), ("Skeleton", "Skeleton"), ("Slime", "Slime"),
    ("Snow Golem", "SnowMan"), ("Spider", "Spider"), ("Squid", "Squid"), ("Villager", "Villager"),
    ("Witch", "Witch"), ("Wither", "WitherBoss"), ("Wolf", "Wolf"), ("Zombie", "Zombie"),
    ("Zombie Pigman", "PigZombie"),
]


def labels(kind="block"):
    return [lbl for lbl, _i, _k in (ITEM_INDEX if kind == "item" else BLOCK_INDEX)]


def id_for_label(label, kind="block"):
    for lbl, i, _k in (ITEM_INDEX if kind == "item" else BLOCK_INDEX):
        if lbl == label:
            return i
    return None


def name_for(i, kind="block"):
    return (ITEM_NAMES if kind == "item" else BLOCK_NAMES).get(int(i))


def search(query, kind="block"):
    """Filtered "Name (id)" labels matching query (by name substring or id prefix)."""
    idx = ITEM_INDEX if kind == "item" else BLOCK_INDEX
    q = str(query).strip().lower()
    if not q:
        return [lbl for lbl, _i, _k in idx]
    hits = [(lbl, i, k) for lbl, i, k in idx if q in k or str(i).startswith(q)]
    hits.sort(key=lambda t: (not t[2].startswith(q), t[1]))
    return [lbl for lbl, _i, _k in hits]


# ---- enchantments / potion effects (LCE numeric ids, pre-flattening 1.12-era) ----
ENCHANT_NAMES = {
    0: "Protection", 1: "Fire Protection", 2: "Feather Falling", 3: "Blast Protection",
    4: "Projectile Protection", 5: "Respiration", 6: "Aqua Affinity", 7: "Thorns",
    8: "Depth Strider", 9: "Frost Walker", 10: "Curse of Binding",
    16: "Sharpness", 17: "Smite", 18: "Bane of Arthropods", 19: "Knockback",
    20: "Fire Aspect", 21: "Looting", 22: "Sweeping Edge",
    32: "Efficiency", 33: "Silk Touch", 34: "Unbreaking", 35: "Fortune",
    48: "Power", 49: "Punch", 50: "Flame", 51: "Infinity",
    61: "Luck of the Sea", 62: "Lure", 70: "Mending", 71: "Curse of Vanishing",
}
ENCHANT_MAX = {           # usual maximum level (others default to 1)
    0: 4, 1: 4, 2: 4, 3: 4, 4: 4, 5: 3, 7: 3, 8: 3, 16: 5, 17: 5, 18: 5, 19: 2,
    20: 2, 21: 3, 22: 3, 32: 5, 34: 3, 35: 3, 48: 5, 49: 2, 61: 3, 62: 3,
}
EFFECT_NAMES = {
    1: "Speed", 2: "Slowness", 3: "Haste", 4: "Mining Fatigue", 5: "Strength",
    6: "Instant Health", 7: "Instant Damage", 8: "Jump Boost", 9: "Nausea",
    10: "Regeneration", 11: "Resistance", 12: "Fire Resistance", 13: "Water Breathing",
    14: "Invisibility", 15: "Blindness", 16: "Night Vision", 17: "Hunger", 18: "Weakness",
    19: "Poison", 20: "Wither", 21: "Health Boost", 22: "Absorption", 23: "Saturation",
    24: "Glowing", 25: "Levitation", 26: "Luck", 27: "Bad Luck",
}
POTION_ITEM_IDS = {373, 438, 441, 440}    # potion, splash, lingering, tipped arrow
POTION_BASES = [
    "minecraft:water", "minecraft:awkward", "minecraft:thick", "minecraft:mundane",
    "minecraft:night_vision", "minecraft:invisibility", "minecraft:leaping",
    "minecraft:fire_resistance", "minecraft:swiftness", "minecraft:slowness",
    "minecraft:water_breathing", "minecraft:healing", "minecraft:harming",
    "minecraft:poison", "minecraft:regeneration", "minecraft:strength",
    "minecraft:weakness", "minecraft:luck", "minecraft:turtle_master",
    "minecraft:slow_falling",
]
